"""Teste detinatarios e emitentes

Revision ID: 02bd0a155362
Revises: c4de4d4a946b
Create Date: 2025-10-23 15:31:03.326398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02bd0a155362'
down_revision: Union[str, Sequence[str], None] = 'c4de4d4a946b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinatarios',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinatarios_cnpj'), 'destinatarios', ['cnpj'], unique=True)
    op.create_index(op.f('ix_destinatarios_email'), 'destinatarios', ['email'], unique=False)
    op.create_index(op.f('ix_destinatarios_nome'), 'destinatarios', ['nome'], unique=False)
    op.create_index(op.f('ix_destinatarios_telefone'), 'destinatarios', ['telefone'], unique=False)
    op.create_table('emitentes',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emitentes_cnpj'), 'emitentes', ['cnpj'], unique=True)
    op.create_index(op.f('ix_emitentes_email'), 'emitentes', ['email'], unique=False)
    op.create_index(op.f('ix_emitentes_nome'), 'emitentes', ['nome'], unique=False)
    op.create_index(op.f('ix_emitentes_telefone'), 'emitentes', ['telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emitentes_telefone'), table_name='emitentes')
    op.drop_index(op.f('ix_emitentes_nome'), table_name='emitentes')
    op.drop_index(op.f('ix_emitentes_email'), table_name='emitentes')
    op.drop_index(op.f('ix_emitentes_cnpj'), table_name='emitentes')
    op.drop_table('emitentes')
    op.drop_index(op.f('ix_destinatarios_telefone'), table_name='destinatarios')
    op.drop_index(op.f('ix_destinatarios_nome'), table_name='destinatarios')
    op.drop_index(op.f('ix_destinatarios_email'), table_name='destinatarios')
    op.drop_index(op.f('ix_destinatarios_cnpj'), table_name='destinatarios')
    op.drop_table('destinatarios')
    # ### end Alembic commands ###
