"""Initial tables

Revision ID: 5537e0cd6c6a
Revises: 
Create Date: 2025-11-04 10:18:19.130728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5537e0cd6c6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinatarios',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinatarios_cpf_cnpj'), 'destinatarios', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_destinatarios_email'), 'destinatarios', ['email'], unique=False)
    op.create_index(op.f('ix_destinatarios_name'), 'destinatarios', ['name'], unique=False)
    op.create_index(op.f('ix_destinatarios_phone'), 'destinatarios', ['phone'], unique=False)
    op.create_table('emitentes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emitentes_cnpj'), 'emitentes', ['cnpj'], unique=True)
    op.create_index(op.f('ix_emitentes_email'), 'emitentes', ['email'], unique=False)
    op.create_index(op.f('ix_emitentes_name'), 'emitentes', ['name'], unique=False)
    op.create_index(op.f('ix_emitentes_phone'), 'emitentes', ['phone'], unique=False)
    op.create_table('nota_fiscal',
    sa.Column('numero_nota', sa.String(length=50), nullable=False),
    sa.Column('serie', sa.String(length=20), nullable=False),
    sa.Column('cfop', sa.String(length=10), nullable=False),
    sa.Column('nome_emitente', sa.String(length=100), nullable=False),
    sa.Column('cnpj_emitente', sa.String(length=18), nullable=False),
    sa.Column('nome_destinatario', sa.String(length=100), nullable=False),
    sa.Column('cpf_ou_cnpj_destinatario', sa.String(length=18), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('icms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cofins', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('nota_fiscal')
    op.drop_index(op.f('ix_emitentes_phone'), table_name='emitentes')
    op.drop_index(op.f('ix_emitentes_name'), table_name='emitentes')
    op.drop_index(op.f('ix_emitentes_email'), table_name='emitentes')
    op.drop_index(op.f('ix_emitentes_cnpj'), table_name='emitentes')
    op.drop_table('emitentes')
    op.drop_index(op.f('ix_destinatarios_phone'), table_name='destinatarios')
    op.drop_index(op.f('ix_destinatarios_name'), table_name='destinatarios')
    op.drop_index(op.f('ix_destinatarios_email'), table_name='destinatarios')
    op.drop_index(op.f('ix_destinatarios_cpf_cnpj'), table_name='destinatarios')
    op.drop_table('destinatarios')
    # ### end Alembic commands ###
