"""Informações da tabela atualizadas

Revision ID: b200b8fddb46
Revises: cf1187b7a576
Create Date: 2025-10-29 13:54:21.060895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b200b8fddb46'
down_revision: Union[str, Sequence[str], None] = 'cf1187b7a576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinatarios_cnpj'), table_name='destinatarios')
    op.create_index(op.f('ix_destinatarios_cpf_cnpj'), 'destinatarios', ['cpf_cnpj'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinatarios_cpf_cnpj'), table_name='destinatarios')
    op.create_index(op.f('ix_destinatarios_cnpj'), 'destinatarios', ['cpf_cnpj'], unique=True)
    # ### end Alembic commands ###
