"""Migração com alterações de emitentes e destinatarios

Revision ID: cf1187b7a576
Revises: 16f4999ad3c2
Create Date: 2025-10-24 16:11:15.670197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1187b7a576'
down_revision: Union[str, Sequence[str], None] = '16f4999ad3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinatarios', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('destinatarios', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('destinatarios', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_index(op.f('ix_destinatarios_nome'), table_name='destinatarios')
    op.drop_index(op.f('ix_destinatarios_telefone'), table_name='destinatarios')
    op.create_index(op.f('ix_destinatarios_name'), 'destinatarios', ['name'], unique=False)
    op.create_index(op.f('ix_destinatarios_phone'), 'destinatarios', ['phone'], unique=False)
    op.drop_column('destinatarios', 'ativo')
    op.drop_column('destinatarios', 'telefone')
    op.drop_column('destinatarios', 'nome')
    op.add_column('emitentes', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('emitentes', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('emitentes', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_index(op.f('ix_emitentes_nome'), table_name='emitentes')
    op.drop_index(op.f('ix_emitentes_telefone'), table_name='emitentes')
    op.create_index(op.f('ix_emitentes_name'), 'emitentes', ['name'], unique=False)
    op.create_index(op.f('ix_emitentes_phone'), 'emitentes', ['phone'], unique=False)
    op.drop_column('emitentes', 'telefone')
    op.drop_column('emitentes', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitentes', sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('emitentes', sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_emitentes_phone'), table_name='emitentes')
    op.drop_index(op.f('ix_emitentes_name'), table_name='emitentes')
    op.create_index(op.f('ix_emitentes_telefone'), 'emitentes', ['telefone'], unique=False)
    op.create_index(op.f('ix_emitentes_nome'), 'emitentes', ['nome'], unique=False)
    op.drop_column('emitentes', 'active')
    op.drop_column('emitentes', 'phone')
    op.drop_column('emitentes', 'name')
    op.add_column('destinatarios', sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('destinatarios', sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('destinatarios', sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_destinatarios_phone'), table_name='destinatarios')
    op.drop_index(op.f('ix_destinatarios_name'), table_name='destinatarios')
    op.create_index(op.f('ix_destinatarios_telefone'), 'destinatarios', ['telefone'], unique=False)
    op.create_index(op.f('ix_destinatarios_nome'), 'destinatarios', ['nome'], unique=False)
    op.drop_column('destinatarios', 'active')
    op.drop_column('destinatarios', 'phone')
    op.drop_column('destinatarios', 'name')
    # ### end Alembic commands ###
